name: JHapy Utils Spring Boot Admin Server K8S CI

on:
  push:
  workflow_dispatch:

env:
  IMAGE_NAME: utils-spring-boot-admin-server

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - run: echo Build for SHA = ${{ github.event.client_payload.sha }}, REF = ${{ github.event.client_payload.ref }}
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.ref }}
      - name: Set up JDK 1.15
        uses: actions/setup-java@v1
        with:
          java-version: 1.15
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: |
            ~/.m2/repository
            !~/.m2/repository/org/jhapy/**
          key: ${{ runner.os }}-maven-utils-spring-boot-admin-server
          restore-keys: |
            ${{ runner.os }}-maven-utils-spring-boot-admin-server
      - name: Clean Maven Repository
        run: rm -rf ~/.m2/repository/org/jhapy
      - name: Log into Docker Hub Registry
        run: echo "${{ secrets.dockerhub_password }}" | docker login --username ${{ secrets.dockerhub_username }}  --password-stdin
      - name: Build with Maven
        run: mvn -Pk8s -Dmaven.test.skip -s .settings.xml -Dmaven.javadoc.skip -Dossrh_username=${{secrets.ossrh_username}} -Dossrh_password=${{secrets.ossrh_password}} --file pom.xml deploy jib:build
      - name: Slack Success
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
        env:
          GITHUB_TOKEN: ${{ github.token }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()